import 'package:shandada/models/activity.dart';
import 'package:shandada/models/feed.dart';
import 'package:shandada/models/user.dart';

class MockData {
  // 用户头像池 - 使用稳定的图片服务
  static final List<String> userAvatars = [
    'https://picsum.photos/150/150?random=1', // 头像1
    'https://picsum.photos/150/150?random=2', // 头像2
    'https://picsum.photos/150/150?random=3', // 头像3
    'https://picsum.photos/150/150?random=4', // 头像4
    'https://picsum.photos/150/150?random=5', // 头像5
    'https://picsum.photos/150/150?random=6', // 头像6
    'https://picsum.photos/150/150?random=7', // 头像7
    'https://picsum.photos/150/150?random=8', // 头像8
    'https://picsum.photos/150/150?random=9', // 头像9
    'https://picsum.photos/150/150?random=10', // 头像10
  ];

  static String getUserAvatar(int index) {
    return userAvatars[index % userAvatars.length];
  }

  // 图片URL池 - 为不同分类提供多样化的图片（每个分类至少15张不同的图片）
  static final Map<String, List<String>> categoryImages = {
    '观影': [
      'https://picsum.photos/400/300?random=101',
      'https://picsum.photos/400/300?random=102',
      'https://picsum.photos/400/300?random=103',
      'https://picsum.photos/400/300?random=104',
      'https://picsum.photos/400/300?random=105',
      'https://picsum.photos/400/300?random=106',
      'https://picsum.photos/400/300?random=107',
      'https://picsum.photos/400/300?random=108',
      'https://picsum.photos/400/300?random=109',
      'https://picsum.photos/400/300?random=110',
      'https://picsum.photos/400/300?random=111',
      'https://picsum.photos/400/300?random=112',
      'https://picsum.photos/400/300?random=113',
      'https://picsum.photos/400/300?random=114',
      'https://picsum.photos/400/300?random=115',
    ],
    '看展': [
      'https://picsum.photos/400/300?random=201',
      'https://picsum.photos/400/300?random=202',
      'https://picsum.photos/400/300?random=203',
      'https://picsum.photos/400/300?random=204',
      'https://picsum.photos/400/300?random=205',
      'https://picsum.photos/400/300?random=206',
      'https://picsum.photos/400/300?random=207',
      'https://picsum.photos/400/300?random=208',
      'https://picsum.photos/400/300?random=209',
      'https://picsum.photos/400/300?random=210',
      'https://picsum.photos/400/300?random=211',
      'https://picsum.photos/400/300?random=212',
      'https://picsum.photos/400/300?random=213',
      'https://picsum.photos/400/300?random=214',
      'https://picsum.photos/400/300?random=215',
    ],
    '品鉴': [
      'https://picsum.photos/400/300?random=301',
      'https://picsum.photos/400/300?random=302',
      'https://picsum.photos/400/300?random=303',
      'https://picsum.photos/400/300?random=304',
      'https://picsum.photos/400/300?random=305',
      'https://picsum.photos/400/300?random=306',
      'https://picsum.photos/400/300?random=307',
      'https://picsum.photos/400/300?random=308',
      'https://picsum.photos/400/300?random=309',
      'https://picsum.photos/400/300?random=310',
      'https://picsum.photos/400/300?random=311',
      'https://picsum.photos/400/300?random=312',
      'https://picsum.photos/400/300?random=313',
      'https://picsum.photos/400/300?random=314',
      'https://picsum.photos/400/300?random=315',
    ],
    '饭局': [
      'https://picsum.photos/400/300?random=401',
      'https://picsum.photos/400/300?random=402',
      'https://picsum.photos/400/300?random=403',
      'https://picsum.photos/400/300?random=404',
      'https://picsum.photos/400/300?random=405',
      'https://picsum.photos/400/300?random=406',
      'https://picsum.photos/400/300?random=407',
      'https://picsum.photos/400/300?random=408',
      'https://picsum.photos/400/300?random=409',
      'https://picsum.photos/400/300?random=410',
      'https://picsum.photos/400/300?random=411',
      'https://picsum.photos/400/300?random=412',
      'https://picsum.photos/400/300?random=413',
      'https://picsum.photos/400/300?random=414',
      'https://picsum.photos/400/300?random=415',
    ],
    '音乐': [
      'https://picsum.photos/400/300?random=501',
      'https://picsum.photos/400/300?random=502',
      'https://picsum.photos/400/300?random=503',
      'https://picsum.photos/400/300?random=504',
      'https://picsum.photos/400/300?random=505',
      'https://picsum.photos/400/300?random=506',
      'https://picsum.photos/400/300?random=507',
      'https://picsum.photos/400/300?random=508',
      'https://picsum.photos/400/300?random=509',
      'https://picsum.photos/400/300?random=510',
      'https://picsum.photos/400/300?random=511',
      'https://picsum.photos/400/300?random=512',
      'https://picsum.photos/400/300?random=513',
      'https://picsum.photos/400/300?random=514',
      'https://picsum.photos/400/300?random=515',
    ],
    '骑行': [
      'https://picsum.photos/400/300?random=601',
      'https://picsum.photos/400/300?random=602',
      'https://picsum.photos/400/300?random=603',
      'https://picsum.photos/400/300?random=604',
      'https://picsum.photos/400/300?random=605',
      'https://picsum.photos/400/300?random=606',
      'https://picsum.photos/400/300?random=607',
      'https://picsum.photos/400/300?random=608',
      'https://picsum.photos/400/300?random=609',
      'https://picsum.photos/400/300?random=610',
      'https://picsum.photos/400/300?random=611',
      'https://picsum.photos/400/300?random=612',
      'https://picsum.photos/400/300?random=613',
      'https://picsum.photos/400/300?random=614',
      'https://picsum.photos/400/300?random=615',
    ],
    '户外': [
      'https://picsum.photos/400/300?random=701',
      'https://picsum.photos/400/300?random=702',
      'https://picsum.photos/400/300?random=703',
      'https://picsum.photos/400/300?random=704',
      'https://picsum.photos/400/300?random=705',
      'https://picsum.photos/400/300?random=706',
      'https://picsum.photos/400/300?random=707',
      'https://picsum.photos/400/300?random=708',
      'https://picsum.photos/400/300?random=709',
      'https://picsum.photos/400/300?random=710',
      'https://picsum.photos/400/300?random=711',
      'https://picsum.photos/400/300?random=712',
      'https://picsum.photos/400/300?random=713',
      'https://picsum.photos/400/300?random=714',
      'https://picsum.photos/400/300?random=715',
    ],
  };

  static String getImageForCategory(String category, int index) {
    final images = categoryImages[category] ?? categoryImages['观影']!;
    return images[index % images.length];
  }

  static final User currentUser = User(
    id: '9051024',
    name: '简简单单',
    bio: '生活本该如此，搭子常伴左右。',
    avatar: 'https://picsum.photos/150/150?random=11',
    followers: 89,
    likes: 3400,
    collections: 248,
    following: 189,
    rating: 4.8,
    publishedActivities: 12,
    participatedActivities: 28,
  );

  static final List<Activity> homeActivities = [
    Activity(
      id: '1',
      title: '当代艺术私享展，寻找周末一起熏陶的艺术搭子',
      description: '周末去看当代艺术展，希望找个志同道合的艺术爱好者一起去。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 0),
      userName: 'Molly',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 142,
      participants: 2,
      distance: 0.8,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 2)),
    ),
    Activity(
      id: '2',
      title: '黑珍珠法餐新菜私密评测局，限2位极度挑剔的饕餮！',
      description: '新开的黑珍珠法餐厅，邀请2位美食家一起品鉴新菜单。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 0),
      userName: 'Jerry',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 89,
      participants: 1,
      distance: 1.5,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 4)),
    ),
    Activity(
      id: '3',
      title: '夜骑长安街！吹吹晚风，破风同行速来',
      description: '今晚7点出发，一起骑行长安街，感受城市夜景。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 0),
      userName: '简简单单',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 320,
      participants: 3,
      distance: 2.1,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 1)),
    ),
    Activity(
      id: '4',
      title: '天幕、落日与不插电民谣。周六星空露营走起',
      description: '周六去郊外露营，带上帐篷和吉他，一起享受自然。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 0),
      userName: '阿木',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 215,
      participants: 4,
      distance: 3.2,
      location: '上海·青浦',
      createdAt: DateTime.now().subtract(Duration(hours: 3)),
    ),
    Activity(
      id: '5',
      title: '周末电影首映，找个聊天舒适的观影搭子',
      description: '新上映的大片首映，希望找个志同道合的电影迷一起看。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 0),
      userName: 'Lily',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 178,
      participants: 2,
      distance: 1.2,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 5)),
    ),
    // 观影 - 新增8条
    Activity(
      id: '6',
      title: '《星际穿越》IMAX重映，找个科幻迷搭子',
      description: '经典科幻大片重映，IMAX视效绝了，找个能聊天的搭子。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 1),
      userName: 'Alex',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 234,
      participants: 1,
      distance: 1.8,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 6)),
    ),
    Activity(
      id: '7',
      title: '文艺电影周末场，寻找有品味的观影搭子',
      description: '小众文艺电影，周末下午场，希望找个能深度讨论的搭子。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 2),
      userName: 'Emma',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 156,
      participants: 0,
      distance: 2.3,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 7)),
    ),
    Activity(
      id: '8',
      title: '恐怖片首映夜场，找个不怕的搭子',
      description: '新恐怖片首映，晚上10点场，需要个胆大的搭子陪我。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 3),
      userName: 'Tom',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 89,
      participants: 1,
      distance: 1.5,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 8)),
    ),
    Activity(
      id: '9',
      title: '动画电影特映会，找个二次元搭子',
      description: '新番动画电影特映，找个喜欢动画的搭子一起看。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 4),
      userName: 'Lisa',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 267,
      participants: 2,
      distance: 0.9,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 9)),
    ),
    Activity(
      id: '10',
      title: '喜剧电影下午场，找个爱笑的搭子',
      description: '新喜剧电影，下午2点场，找个能一起笑的搭子。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 5),
      userName: 'Jack',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 198,
      participants: 1,
      distance: 1.3,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 10)),
    ),
    Activity(
      id: '11',
      title: '爱情电影首映，找个浪漫的搭子',
      description: '新爱情电影首映，晚上7点场，找个能一起感受浪漫的搭子。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 6),
      userName: 'Sarah',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 312,
      participants: 1,
      distance: 2.1,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 11)),
    ),
    Activity(
      id: '12',
      title: '冒险电影周末场，找个爱冒险的搭子',
      description: '新冒险电影，周末晚上8点场，找个热爱冒险的搭子。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 7),
      userName: 'Mike',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 245,
      participants: 2,
      distance: 1.7,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 12)),
    ),
    Activity(
      id: '13',
      title: '悬疑电影特映，找个爱推理的搭子',
      description: '新悬疑电影，周五晚上9点场，找个喜欢推理的搭子。',
      category: '观影',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('观影', 8),
      userName: 'Nina',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 276,
      participants: 0,
      distance: 2.5,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 13)),
    ),
    // 看展 - 新增8条
    Activity(
      id: '14',
      title: '印象派大师展，找个艺术爱好者',
      description: '莫奈、雷诺阿等大师作品展，周末去看，找个能聊艺术的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 1),
      userName: 'David',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 289,
      participants: 1,
      distance: 1.4,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 14)),
    ),
    Activity(
      id: '15',
      title: '当代装置艺术展，寻找艺术思想家',
      description: '新锐艺术家装置艺术展，周末下午，找个能深度讨论的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 2),
      userName: 'Grace',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 201,
      participants: 0,
      distance: 1.9,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 15)),
    ),
    Activity(
      id: '16',
      title: '摄影艺术展，找个有审美的搭子',
      description: '国际摄影艺术展，周五晚上开放，找个有审美的搭子一起看。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 3),
      userName: 'Henry',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 167,
      participants: 1,
      distance: 2.2,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 16)),
    ),
    Activity(
      id: '17',
      title: '雕塑艺术展，找个懂艺术的搭子',
      description: '古今中外雕塑艺术展，周末全天开放，找个懂艺术的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 4),
      userName: 'Iris',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 234,
      participants: 2,
      distance: 1.6,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 17)),
    ),
    Activity(
      id: '18',
      title: '书法艺术展，找个文化爱好者',
      description: '古代书法大家作品展，周末下午，找个喜欢文化的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 5),
      userName: 'Jack',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 198,
      participants: 0,
      distance: 1.8,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 18)),
    ),
    Activity(
      id: '19',
      title: '油画艺术展，找个艺术鉴赏家',
      description: '当代油画艺术展，周五晚上开放，找个能鉴赏艺术的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 6),
      userName: 'Karen',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 267,
      participants: 1,
      distance: 2.3,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 19)),
    ),
    Activity(
      id: '20',
      title: '陶艺艺术展，找个手工爱好者',
      description: '陶艺艺术展，周末全天，找个喜欢手工艺术的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 7),
      userName: 'Leo',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 245,
      participants: 2,
      distance: 1.5,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 20)),
    ),
    Activity(
      id: '22',
      title: '米其林餐厅品鉴，找个美食家',
      description: '新获米其林星的餐厅，周末晚餐，找个懂美食的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 1),
      userName: 'Oliver',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 298,
      participants: 1,
      distance: 1.7,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 22)),
    ),
    Activity(
      id: '23',
      title: '葡萄酒品鉴会，找个酒类爱好者',
      description: '法国葡萄酒品鉴会，周五晚上，找个喜欢红酒的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 2),
      userName: 'Pam',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 267,
      participants: 0,
      distance: 2.4,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 23)),
    ),
    Activity(
      id: '24',
      title: '日本料理品鉴，找个日料爱好者',
      description: '高级日本料理店，周末午餐，找个懂日料的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 3),
      userName: 'Quinn',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 234,
      participants: 1,
      distance: 1.9,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 24)),
    ),
    Activity(
      id: '25',
      title: '茶艺品鉴，找个茶文化爱好者',
      description: '高级茶艺馆，周末下午，找个懂茶的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 4),
      userName: 'Rachel',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 201,
      participants: 2,
      distance: 1.3,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 25)),
    ),
    Activity(
      id: '26',
      title: '咖啡品鉴会，找个咖啡爱好者',
      description: '精品咖啡品鉴会，周五晚上，找个喜欢咖啡的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 5),
      userName: 'Steve',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 256,
      participants: 1,
      distance: 2.2,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 26)),
    ),
    Activity(
      id: '27',
      title: '巧克力品鉴，找个甜品爱好者',
      description: '比利时巧克力品鉴，周末下午，找个喜欢甜品的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 6),
      userName: 'Tina',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 223,
      participants: 0,
      distance: 1.6,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 27)),
    ),
    Activity(
      id: '28',
      title: '烈酒品鉴，找个烈酒爱好者',
      description: '世界烈酒品鉴会，周五晚上，找个喜欢烈酒的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 7),
      userName: 'Uma',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 289,
      participants: 1,
      distance: 2.5,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 28)),
    ),
    Activity(
      id: '29',
      title: '美食品鉴之旅，找个吃货搭子',
      description: '多家餐厅美食品鉴之旅，周末全天，找个热爱美食的搭子。',
      category: '品鉴',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('品鉴', 8),
      userName: 'Victor',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 312,
      participants: 2,
      distance: 1.8,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 29)),
    ),
    // 饭局 - 新增8条
    Activity(
      id: '30',
      title: '火锅聚餐，找个爱吃火锅的搭子',
      description: '周末火锅聚餐，找个能吃辣的搭子一起去。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 0),
      userName: 'Wendy',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 267,
      participants: 3,
      distance: 1.4,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 30)),
    ),
    Activity(
      id: '31',
      title: '烧烤聚餐，找个烧烤爱好者',
      description: '周末烧烤聚餐，找个喜欢烧烤的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 1),
      userName: 'Xavier',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 234,
      participants: 2,
      distance: 2.1,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 31)),
    ),
    Activity(
      id: '32',
      title: '自助餐聚餐，找个吃货搭子',
      description: '周末自助餐聚餐，找个能吃的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 2),
      userName: 'Yara',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 201,
      participants: 1,
      distance: 1.7,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 32)),
    ),
    Activity(
      id: '33',
      title: '海鲜大餐，找个海鲜爱好者',
      description: '周末海鲜大餐，找个喜欢吃海鲜的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 3),
      userName: 'Zoe',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 289,
      participants: 2,
      distance: 2.3,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 33)),
    ),
    Activity(
      id: '34',
      title: '川菜聚餐，找个川菜爱好者',
      description: '周末川菜聚餐，找个喜欢川菜的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 4),
      userName: 'Aaron',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 256,
      participants: 1,
      distance: 1.9,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 34)),
    ),
    Activity(
      id: '35',
      title: '粤菜聚餐，找个粤菜爱好者',
      description: '周末粤菜聚餐，找个喜欢粤菜的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 5),
      userName: 'Bella',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 223,
      participants: 0,
      distance: 2.2,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 35)),
    ),
    Activity(
      id: '36',
      title: '意大利餐聚餐，找个意餐爱好者',
      description: '周末意大利餐聚餐，找个喜欢意餐的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 6),
      userName: 'Chloe',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 267,
      participants: 2,
      distance: 1.5,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 36)),
    ),
    Activity(
      id: '38',
      title: '摇滚演唱会，找个摇滚迷搭子',
      description: '周末摇滚演唱会，找个喜欢摇滚的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 0),
      userName: 'Evan',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 312,
      participants: 2,
      distance: 1.8,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 38)),
    ),
    Activity(
      id: '36',
      title: '意大利餐聚餐，找个意餐爱好者',
      description: '周末意大利餐聚餐，找个喜欢意餐的搭子。',
      category: '饭局',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('饭局', 6),
      userName: 'Chloe',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 267,
      participants: 2,
      distance: 1.5,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 36)),
    ),
    Activity(
      id: '38',
      title: '摇滚演唱会，找个摇滚迷搭子',
      description: '周末摇滚演唱会，找个喜欢摇滚的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 0),
      userName: 'Evan',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 312,
      participants: 2,
      distance: 1.8,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 38)),
    ),
    Activity(
      id: '39',
      title: '爵士音乐会，找个爵士爱好者',
      description: '周末爵士音乐会，找个喜欢爵士的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 1),
      userName: 'Fiona',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 267,
      participants: 1,
      distance: 2.1,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 39)),
    ),
    Activity(
      id: '40',
      title: '民谣音乐会，找个民谣爱好者',
      description: '周末民谣音乐会，找个喜欢民谣的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 2),
      userName: 'George',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 234,
      participants: 0,
      distance: 1.9,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 40)),
    ),
    Activity(
      id: '41',
      title: '古典音乐会，找个古典爱好者',
      description: '周末古典音乐会，找个喜欢古典音乐的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 3),
      userName: 'Hannah',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 289,
      participants: 1,
      distance: 2.3,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 41)),
    ),
    Activity(
      id: '42',
      title: '电子音乐节，找个电音爱好者',
      description: '周末电子音乐节，找个喜欢电子音乐的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 4),
      userName: 'Isaac',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 256,
      participants: 2,
      distance: 1.6,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 42)),
    ),
    Activity(
      id: '43',
      title: '流行音乐演唱会，找个流行迷',
      description: '周末流行音乐演唱会，找个喜欢流行音乐的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 5),
      userName: 'Julia',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 223,
      participants: 1,
      distance: 2.2,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 43)),
    ),
    Activity(
      id: '44',
      title: '说唱演唱会，找个说唱爱好者',
      description: '周末说唱演唱会，找个喜欢说唱的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 6),
      userName: 'Kevin',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 298,
      participants: 0,
      distance: 1.7,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 44)),
    ),
    Activity(
      id: '45',
      title: '民族音乐会，找个民族音乐爱好者',
      description: '周末民族音乐会，找个喜欢民族音乐的搭子。',
      category: '音乐',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('音乐', 7),
      userName: 'Laura',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 267,
      participants: 1,
      distance: 2.4,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 45)),
    ),
    // 骑行 - 新增8条
    Activity(
      id: '46',
      title: '山地骑行，找个骑行爱好者',
      description: '周末山地骑行，找个体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 1),
      userName: 'Mike',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 312,
      participants: 2,
      distance: 1.5,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 46)),
    ),
    Activity(
      id: '47',
      title: '公路骑行，找个速度相近的骑友',
      description: '周末公路骑行，找个速度相近的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 2),
      userName: 'Nancy',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 267,
      participants: 1,
      distance: 2.1,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 47)),
    ),
    Activity(
      id: '48',
      title: '城市骑行，找个骑行搭子',
      description: '周末城市骑行，找个喜欢骑行的搭子。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 3),
      userName: 'Oscar',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 234,
      participants: 0,
      distance: 1.8,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 48)),
    ),
    Activity(
      id: '49',
      title: '夜间骑行，找个夜骑爱好者',
      description: '周末夜间骑行，找个喜欢夜骑的搭子。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 4),
      userName: 'Pam',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 289,
      participants: 2,
      distance: 2.3,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 49)),
    ),
    Activity(
      id: '50',
      title: '长距离骑行，找个耐力型骑友',
      description: '周末长距离骑行，找个体能好的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 5),
      userName: 'Quinn',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 256,
      participants: 1,
      distance: 1.9,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 50)),
    ),
    Activity(
      id: '51',
      title: '休闲骑行，找个骑行搭子',
      description: '周末休闲骑行，找个喜欢骑行的搭子。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 6),
      userName: 'Rachel',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 223,
      participants: 0,
      distance: 2.2,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 51)),
    ),
    Activity(
      id: '52',
      title: '竞速骑行，找个竞速爱好者',
      description: '周末竞速骑行，找个喜欢竞速的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 7),
      userName: 'Steve',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 298,
      participants: 1,
      distance: 1.6,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 52)),
    ),
    Activity(
      id: '53',
      title: '环岛骑行，找个骑行搭子',
      description: '周末环岛骑行，找个喜欢骑行的搭子。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 8),
      userName: 'Tina',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 267,
      participants: 2,
      distance: 2.4,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 53)),
    ),
    // 户外 - 新增8条
    Activity(
      id: '54',
      title: '登山活动，找个登山爱好者',
      description: '周末登山，找个体能不错的登山爱好者。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 1),
      userName: 'Uma',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 312,
      participants: 2,
      distance: 1.7,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 54)),
    ),
    Activity(
      id: '55',
      title: '露营活动，找个露营爱好者',
      description: '周末露营，找个喜欢露营的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 2),
      userName: 'Victor',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 267,
      participants: 1,
      distance: 2.1,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 55)),
    ),
    Activity(
      id: '56',
      title: '徒步活动，找个徒步爱好者',
      description: '周末徒步，找个喜欢徒步的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 3),
      userName: 'Wendy',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 234,
      participants: 0,
      distance: 1.9,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 56)),
    ),
    Activity(
      id: '57',
      title: '野餐活动，找个野餐爱好者',
      description: '周末野餐，找个喜欢野餐的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 4),
      userName: 'Xavier',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 289,
      participants: 2,
      distance: 2.3,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 57)),
    ),
    Activity(
      id: '58',
      title: '钓鱼活动，找个钓鱼爱好者',
      description: '周末钓鱼，找个喜欢钓鱼的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 5),
      userName: 'Yara',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 256,
      participants: 1,
      distance: 1.8,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 58)),
    ),
    Activity(
      id: '59',
      title: '摄影采风，找个摄影爱好者',
      description: '周末摄影采风，找个喜欢摄影的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 6),
      userName: 'Zoe',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 223,
      participants: 0,
      distance: 2.2,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 59)),
    ),
    Activity(
      id: '60',
      title: '滑翔伞活动，找个滑翔伞爱好者',
      description: '周末滑翔伞，找个喜欢滑翔伞的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 7),
      userName: 'Aaron',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 298,
      participants: 1,
      distance: 2.4,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 60)),
    ),
    Activity(
      id: '61',
      title: '漂流活动，找个漂流爱好者',
      description: '周末漂流，找个喜欢漂流的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 8),
      userName: 'Bella',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 267,
      participants: 2,
      distance: 1.6,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 61)),
    ),
  ];

  static final List<Activity> buddyActivities = [
    Activity(
      id: 'b1',
      title: '有无有氧上网网球搭子？今晚7点静安体育中心',
      description: '目前已有2人，都是友好型小白。希望再来1-2个水平相近的小伙伴一同快乐拉开，AA场地费。',
      category: '球类',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('球类', 0),
      userName: 'Tom',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 2,
      distance: 1.2,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 1)),
      isFull: false,
    ),
    Activity(
      id: 'b2',
      title: '新晋网红黑胶咖啡厅打卡，找个会拍照的小姐姐',
      description: '买到了珍藏版黑胶，准备下午去叹咖啡聊天。本人带专业微单，出片率极高！',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 0),
      userName: 'Sarah',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 2.8,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 2)),
      isFull: false,
    ),
    Activity(
      id: 'b3',
      title: '周末骑行环浦东，找个速度相近的骑友',
      description: '计划周日早上8点出发，骑行环浦东一圈，大约80km。需要体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 0),
      userName: '阿杰',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 1,
      distance: 0.5,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 3)),
      isFull: false,
    ),
    Activity(
      id: 'b4',
      title: '周末露营+篝火，寻找热爱户外的小伙伴',
      description: '计划周末去崇明岛露营，带帐篷、睡袋、烧烤工具。需要2-3个热爱户外的朋友。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 0),
      userName: '小李',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 1,
      distance: 3.5,
      location: '上海·崇明',
      createdAt: DateTime.now().subtract(Duration(hours: 4)),
      isFull: false,
    ),
    Activity(
      id: 'b5',
      title: '周五晚上看展，寻找艺术爱好者',
      description: '新开的当代艺术展，周五晚上去看，希望找个能聊天的艺术爱好者。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 0),
      userName: '小美',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 0,
      distance: 1.8,
      location: '上海·黄浦',
      createdAt: DateTime.now().subtract(Duration(hours: 5)),
      isFull: false,
    ),
    Activity(
      id: 'b6',
      title: '周末钓鱼，寻找钓鱼爱好者',
      description: '周末去青浦钓鱼，需要2-3个钓鱼爱好者，一起享受钓鱼的乐趣。',
      category: '垂钓',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('垂钓', 0),
      userName: '老王',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 4.2,
      location: '上海·青浦',
      createdAt: DateTime.now().subtract(Duration(hours: 6)),
      isFull: false,
    ),
    Activity(
      id: 'b7',
      title: '周六舞蹈课，寻找舞蹈搭子',
      description: '报了爵士舞课程，希望找个一起学舞蹈的搭子，互相鼓励。',
      category: '舞蹈',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('舞蹈', 0),
      userName: '小红',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 0,
      distance: 2.1,
      location: '上海·徐汇',
      createdAt: DateTime.now().subtract(Duration(hours: 7)),
      isFull: false,
    ),
    Activity(
      id: 'b8',
      title: '健身房打卡，寻找健身搭子',
      description: '每周三五晚上去健身房，希望找个一起健身的搭子，互相监督。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 0),
      userName: '健身达人',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 2,
      distance: 0.8,
      location: '上海·浦东',
      createdAt: DateTime.now().subtract(Duration(hours: 8)),
      isFull: false,
    ),
    Activity(
      id: 'b9',
      title: '桌游聚会，寻找桌游爱好者',
      description: '周末组织桌游聚会，需要4-6个桌游爱好者，一起享受桌游的乐趣。',
      category: '桌游',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('桌游', 0),
      userName: '游戏达人',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 3,
      distance: 1.5,
      location: '上海·静安',
      createdAt: DateTime.now().subtract(Duration(hours: 9)),
      isFull: false,
    ),
    Activity(
      id: 'b10',
      title: '美食探店，寻找吃货搭子',
      description: '最近发现了几家不错的餐厅，想找个一起探店的吃货搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 1),
      userName: '美食家',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 2.3,
      location: '上海·长宁',
      createdAt: DateTime.now().subtract(Duration(hours: 10)),
      isFull: false,
    ),
    // 北京 - 新增5条
    Activity(
      id: 'b11',
      title: '798艺术区看展，找个艺术爱好者',
      description: '周末去798艺术区看展，希望找个能深度讨论艺术的搭子。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 1),
      userName: '艺术迷',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 0,
      distance: 2.5,
      location: '北京·朝阳',
      createdAt: DateTime.now().subtract(Duration(hours: 11)),
      isFull: false,
    ),
    Activity(
      id: 'b12',
      title: '颐和园骑行，找个骑友',
      description: '周末骑行颐和园周边，需要体能不错的骑友，一起享受骑行的乐趣。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 1),
      userName: '骑行达人',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 2,
      distance: 3.2,
      location: '北京·海淀',
      createdAt: DateTime.now().subtract(Duration(hours: 12)),
      isFull: false,
    ),
    Activity(
      id: 'b13',
      title: '健身房打卡，找个健身搭子',
      description: '每周二四晚上去健身房，希望找个一起健身的搭子。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 1),
      userName: '健身小姐姐',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 1,
      distance: 1.8,
      location: '北京·东城',
      createdAt: DateTime.now().subtract(Duration(hours: 13)),
      isFull: false,
    ),
    Activity(
      id: 'b14',
      title: '簋街美食探店，找个吃货',
      description: '周末去簋街探店，想找个会吃、会拍照的吃货搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 2),
      userName: '美食博主',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 2.1,
      location: '北京·朝阳',
      createdAt: DateTime.now().subtract(Duration(hours: 14)),
      isFull: false,
    ),
    Activity(
      id: 'b15',
      title: '桌游聚会，找个桌游爱好者',
      description: '周末组织桌游聚会，需要3-4个桌游爱好者。',
      category: '桌游',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('桌游', 1),
      userName: '游戏迷',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 2,
      distance: 1.5,
      location: '北京·西城',
      createdAt: DateTime.now().subtract(Duration(hours: 15)),
      isFull: false,
    ),
    // 广州 - 新增5条
    Activity(
      id: 'b16',
      title: '珠江夜骑，找个骑友',
      description: '周末晚上沿珠江骑行，需要体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 2),
      userName: '骑行爱好者',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 1,
      distance: 2.8,
      location: '广州·天河',
      createdAt: DateTime.now().subtract(Duration(hours: 16)),
      isFull: false,
    ),
    Activity(
      id: 'b17',
      title: '美食街探店，找个吃货搭子',
      description: '周末去美食街探店，想找个会吃的搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 3),
      userName: '吃货',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 0,
      distance: 1.9,
      location: '广州·越秀',
      createdAt: DateTime.now().subtract(Duration(hours: 17)),
      isFull: false,
    ),
    Activity(
      id: 'b18',
      title: '户外露营，找个户外爱好者',
      description: '周末去从化露营，需要热爱户外的小伙伴。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 1),
      userName: '户外达人',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 2,
      distance: 3.5,
      location: '广州·从化',
      createdAt: DateTime.now().subtract(Duration(hours: 18)),
      isFull: false,
    ),
    Activity(
      id: 'b19',
      title: '看展找搭子，艺术爱好者',
      description: '周末去美术馆看展，找个能聊天的艺术爱好者。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 2),
      userName: '艺术家',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 0,
      distance: 2.2,
      location: '广州·海珠',
      createdAt: DateTime.now().subtract(Duration(hours: 19)),
      isFull: false,
    ),
    Activity(
      id: 'b20',
      title: '健身房打卡，找个健身搭子',
      description: '每周三五晚上去健身房，找个一起健身的搭子。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 2),
      userName: '健身教练',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 1,
      distance: 1.5,
      location: '广州·天河',
      createdAt: DateTime.now().subtract(Duration(hours: 20)),
      isFull: false,
    ),
    // 深圳 - 新增5条
    Activity(
      id: 'b21',
      title: '大梅沙冲浪，找个冲浪爱好者',
      description: '周末去大梅沙冲浪，需要有冲浪经验的搭子。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 2),
      userName: '冲浪爱好者',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 1,
      distance: 2.3,
      location: '深圳·盐田',
      createdAt: DateTime.now().subtract(Duration(hours: 21)),
      isFull: false,
    ),
    Activity(
      id: 'b22',
      title: '文创园看展，找个艺术爱好者',
      description: '周末去文创园看展，找个能聊天的艺术爱好者。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 3),
      userName: '艺术迷',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 0,
      distance: 1.8,
      location: '深圳·南山',
      createdAt: DateTime.now().subtract(Duration(hours: 22)),
      isFull: false,
    ),
    Activity(
      id: 'b23',
      title: '骑行环深圳湾，找个骑友',
      description: '周末骑行环深圳湾，需要体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 3),
      userName: '骑行达人',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 2,
      distance: 2.1,
      location: '深圳·南山',
      createdAt: DateTime.now().subtract(Duration(hours: 23)),
      isFull: false,
    ),
    Activity(
      id: 'b24',
      title: '美食探店，找个吃货搭子',
      description: '周末去华强北美食街探店，找个会吃的搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 4),
      userName: '美食家',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 1,
      distance: 1.5,
      location: '深圳·福田',
      createdAt: DateTime.now().subtract(Duration(hours: 24)),
      isFull: false,
    ),
    Activity(
      id: 'b25',
      title: '健身房打卡，找个健身搭子',
      description: '每周二四晚上去健身房，找个一起健身的搭子。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 3),
      userName: '健身小哥',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 1,
      distance: 1.2,
      location: '深圳·福田',
      createdAt: DateTime.now().subtract(Duration(hours: 25)),
      isFull: false,
    ),
    // 杭州 - 新增5条
    Activity(
      id: 'b26',
      title: '西湖骑行，找个骑友',
      description: '周末沿西湖骑行，需要体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 4),
      userName: '骑行爱好者',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 2.0,
      location: '杭州·西湖',
      createdAt: DateTime.now().subtract(Duration(hours: 26)),
      isFull: false,
    ),
    Activity(
      id: 'b27',
      title: '美食探店，找个吃货搭子',
      description: '周末去河坊街探店，找个会吃的搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 5),
      userName: '吃货',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 0,
      distance: 1.7,
      location: '杭州·上城',
      createdAt: DateTime.now().subtract(Duration(hours: 27)),
      isFull: false,
    ),
    Activity(
      id: 'b28',
      title: '看展找搭子，艺术爱好者',
      description: '周末去美术馆看展，找个能聊天的艺术爱好者。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 4),
      userName: '艺术家',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 0,
      distance: 2.3,
      location: '杭州·上城',
      createdAt: DateTime.now().subtract(Duration(hours: 28)),
      isFull: false,
    ),
    Activity(
      id: 'b29',
      title: '户外露营，找个户外爱好者',
      description: '周末去龙坞露营，需要热爱户外的小伙伴。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 3),
      userName: '户外达人',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 2,
      distance: 3.0,
      location: '杭州·西湖',
      createdAt: DateTime.now().subtract(Duration(hours: 29)),
      isFull: false,
    ),
    Activity(
      id: 'b30',
      title: '健身房打卡，找个健身搭子',
      description: '每周三五晚上去健身房，找个一起健身的搭子。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 4),
      userName: '健身教练',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 1.3,
      location: '杭州·滨江',
      createdAt: DateTime.now().subtract(Duration(hours: 30)),
      isFull: false,
    ),
    // 南京 - 新增5条
    Activity(
      id: 'b31',
      title: '秦淮河骑行，找个骑友',
      description: '周末沿秦淮河骑行，需要体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 5),
      userName: '骑行爱好者',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 1,
      distance: 2.2,
      location: '南京·秦淮',
      createdAt: DateTime.now().subtract(Duration(hours: 31)),
      isFull: false,
    ),
    Activity(
      id: 'b32',
      title: '美食探店，找个吃货搭子',
      description: '周末去夫子庙美食街探店，找个会吃的搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 6),
      userName: '美食家',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 0,
      distance: 1.8,
      location: '南京·秦淮',
      createdAt: DateTime.now().subtract(Duration(hours: 32)),
      isFull: false,
    ),
    Activity(
      id: 'b33',
      title: '看展找搭子，艺术爱好者',
      description: '周末去美术馆看展，找个能聊天的艺术爱好者。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 5),
      userName: '艺术迷',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 0,
      distance: 2.1,
      location: '南京·玄武',
      createdAt: DateTime.now().subtract(Duration(hours: 33)),
      isFull: false,
    ),
    Activity(
      id: 'b34',
      title: '健身房打卡，找个健身搭子',
      description: '每周二四晚上去健身房，找个一起健身的搭子。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 5),
      userName: '健身小姐姐',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 1,
      distance: 1.5,
      location: '南京·鼓楼',
      createdAt: DateTime.now().subtract(Duration(hours: 34)),
      isFull: false,
    ),
    Activity(
      id: 'b35',
      title: '户外露营，找个户外爱好者',
      description: '周末去汤山露营，需要热爱户外的小伙伴。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 4),
      userName: '户外达人',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 2,
      distance: 3.2,
      location: '南京·江宁',
      createdAt: DateTime.now().subtract(Duration(hours: 35)),
      isFull: false,
    ),
    // 苏州 - 新增5条
    Activity(
      id: 'b36',
      title: '古城骑行，找个骑友',
      description: '周末骑行苏州古城，需要体能不错的骑友。',
      category: '骑行',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('骑行', 6),
      userName: '骑行爱好者',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 1,
      distance: 2.0,
      location: '苏州·姑苏',
      createdAt: DateTime.now().subtract(Duration(hours: 36)),
      isFull: false,
    ),
    Activity(
      id: 'b37',
      title: '美食探店，找个吃货搭子',
      description: '周末去平江路美食街探店，找个会吃的搭子。',
      category: '探店',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('探店', 7),
      userName: '吃货',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      likes: 0,
      participants: 0,
      distance: 1.6,
      location: '苏州·姑苏',
      createdAt: DateTime.now().subtract(Duration(hours: 37)),
      isFull: false,
    ),
    Activity(
      id: 'b38',
      title: '看展找搭子，艺术爱好者',
      description: '周末去美术馆看展，找个能聊天的艺术爱好者。',
      category: '看展',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('看展', 6),
      userName: '艺术家',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      likes: 0,
      participants: 0,
      distance: 2.2,
      location: '苏州·工业园',
      createdAt: DateTime.now().subtract(Duration(hours: 38)),
      isFull: false,
    ),
    Activity(
      id: 'b39',
      title: '健身房打卡，找个健身搭子',
      description: '每周三五晚上去健身房，找个一起健身的搭子。',
      category: '健身',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('健身', 6),
      userName: '健身教练',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      likes: 0,
      participants: 1,
      distance: 1.4,
      location: '苏州·工业园',
      createdAt: DateTime.now().subtract(Duration(hours: 39)),
      isFull: false,
    ),
    Activity(
      id: 'b40',
      title: '户外露营，找个户外爱好者',
      description: '周末去太湖露营，需要热爱户外的小伙伴。',
      category: '户外',
      categoryEmoji: '🎬',
      imageUrl: MockData.getImageForCategory('户外', 5),
      userName: '户外达人',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      likes: 0,
      participants: 2,
      distance: 2.8,
      location: '苏州·吴中',
      createdAt: DateTime.now().subtract(Duration(hours: 40)),
      isFull: false,
    ),
  ];

  static final List<Feed> feeds = [
    Feed(
      id: 'f_my1',
      userName: '简简单单',
      userAvatar: 'https://picsum.photos/150/150?random=11',
      rating: 5.0,
      ratingLabel: '完美搭子',
      title: '周末咖啡馆打卡，找到了超棒的咖啡搭子 ☕️✨',
      description: '今天和搭子一起去了新开的咖啡馆，聊了很多关于生活和梦想的话题。这种感觉真的太好了，期待下次再约！',
      images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80'],
      category: '咖啡品鉴',
      categoryEmoji: '☕',
      likes: 234,
      comments: 5,
      createdAt: DateTime.now().subtract(Duration(hours: 1)),
      commentList: [
        {
          'userName': '林糖糖 ✨',
          'userAvatar': 'https://picsum.photos/100/100?random=22',
          'content': '这家咖啡馆我也去过，环境真的很棒！',
          'time': '50分钟前',
        },
        {
          'userName': 'Kevin 大大',
          'userAvatar': 'https://picsum.photos/100/100?random=24',
          'content': '下次带我一起去呀',
          'time': '40分钟前',
        },
        {
          'userName': '小美美',
          'userAvatar': 'https://picsum.photos/100/100?random=23',
          'content': '看起来很不错的样子',
          'time': '30分钟前',
        },
        {
          'userName': '废话文学家',
          'userAvatar': 'https://picsum.photos/100/100?random=27',
          'content': '咖啡搭子真的很重要！',
          'time': '20分钟前',
        },
        {
          'userName': 'Dust',
          'userAvatar': 'https://picsum.photos/100/100?random=28',
          'content': '求地址！',
          'time': '10分钟前',
        },
      ],
    ),
    Feed(
      id: 'f_my2',
      userName: '简简单单',
      userAvatar: 'https://picsum.photos/150/150?random=11',
      rating: 4.8,
      ratingLabel: '超赞',
      title: '夜跑打卡！今晚的月亮真美 🌙🏃',
      description: '和运动搭子一起夜跑，沿着江边跑了5公里。晚风吹着特别舒服，运动完整个人都神清气爽！生活需要这样的仪式感。',
      images: ['https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&q=80'],
      category: '运动健身',
      categoryEmoji: '🏃',
      likes: 189,
      comments: 4,
      createdAt: DateTime.now().subtract(Duration(hours: 6)),
      commentList: [
        {
          'userName': '帅到被判无期',
          'userAvatar': 'https://picsum.photos/100/100?random=30',
          'content': '夜跑真的很舒服！',
          'time': '4小时前',
        },
        {
          'userName': '贝贝',
          'userAvatar': 'https://picsum.photos/100/100?random=31',
          'content': '我也想加入夜跑队伍',
          'time': '3小时前',
        },
        {
          'userName': '寄与风',
          'userAvatar': 'https://picsum.photos/100/100?random=32',
          'content': '坚持运动的人最棒了！',
          'time': '2小时前',
        },
        {
          'userName': '春山',
          'userAvatar': 'https://picsum.photos/100/100?random=33',
          'content': '江边夜跑确实很美',
          'time': '1小时前',
        },
      ],
    ),
    Feed(
      id: 'f1',
      userName: '林糖糖 ✨',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      rating: 5.0,
      ratingLabel: '完美搭子',
      title: '昨晚和电影搭子看完首映啦！😊 超级合拍',
      description: '在知陌上找的第一个看电影搭子，对导演风格的理解神同步！全网零代沟，观影全程无手机亮光，极度舒适！',
      images: ['https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&q=80'],
      category: '电影局回馈',
      categoryEmoji: '🍿',
      likes: 1402,
      comments: 3,
      createdAt: DateTime.now().subtract(Duration(hours: 3)),
      commentList: [
        {
          'userName': '废话文学家',
          'userAvatar': 'https://picsum.photos/100/100?random=27',
          'content': '这个活动看起来很不错，我也想参加！',
          'time': '2小时前',
        },
        {
          'userName': 'Dust',
          'userAvatar': 'https://picsum.photos/100/100?random=28',
          'content': '请问具体时间是什么时候呢？',
          'time': '1小时前',
        },
        {
          'userName': '小甜柚',
          'userAvatar': 'https://picsum.photos/100/100?random=29',
          'content': '我上次参加过类似的活动，非常有趣！',
          'time': '30分钟前',
        },
      ],
    ),
    Feed(
      id: 'f2',
      userName: 'Kevin 大大',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      rating: 4.9,
      ratingLabel: '超赞',
      title: '沉浸式飞盘新体验，暴汗局完满结束 😊🦾',
      description: '吹爆我们这次闪搭出的飞盘局！匹配到的大家体能组织力都在线，完全没有尴尬期，给社区环境点赞！评分必须拉满！',
      images: ['https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&q=80'],
      category: '健身飞盘',
      categoryEmoji: '🥏',
      likes: 753,
      comments: 4,
      createdAt: DateTime.now().subtract(Duration(hours: 5)),
      commentList: [
        {
          'userName': '帅到被判无期',
          'userAvatar': 'https://picsum.photos/100/100?random=30',
          'content': '飞盘运动真的很有趣！',
          'time': '3小时前',
        },
        {
          'userName': '贝贝',
          'userAvatar': 'https://picsum.photos/100/100?random=31',
          'content': '下次一起去玩吧！',
          'time': '2小时前',
        },
        {
          'userName': '寄与风',
          'userAvatar': 'https://picsum.photos/100/100?random=32',
          'content': '这个搭子真的很靠谱',
          'time': '1小时前',
        },
        {
          'userName': '春山',
          'userAvatar': 'https://picsum.photos/100/100?random=33',
          'content': '我也想加入！',
          'time': '45分钟前',
        },
      ],
    ),
    Feed(
      id: 'f3',
      userName: '小美美',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      rating: 5.0,
      ratingLabel: '完美搭子',
      title: '艺术展览之旅，找到了灵魂伙伴 🎨✨',
      description: '和搭子一起看了当代艺术展，讨论艺术作品的时候完全停不下来。这就是我想要的搭子体验！',
      images: ['https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=400&q=80'],
      category: '艺术展览',
      categoryEmoji: '🎨',
      likes: 892,
      comments: 3,
      createdAt: DateTime.now().subtract(Duration(hours: 7)),
      commentList: [
        {
          'userName': '沉默的回声',
          'userAvatar': 'https://picsum.photos/100/100?random=34',
          'content': '艺术展览真的很有意思',
          'time': '4小时前',
        },
        {
          'userName': '脑子有黑洞',
          'userAvatar': 'https://picsum.photos/100/100?random=35',
          'content': '我也喜欢看艺术展',
          'time': '3小时前',
        },
        {
          'userName': '扫地僧',
          'userAvatar': 'https://picsum.photos/100/100?random=36',
          'content': '下次一起去看展吧',
          'time': '2小时前',
        },
      ],
    ),
    Feed(
      id: 'f4',
      userName: 'Alex',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      rating: 4.8,
      ratingLabel: '很赞',
      title: '周末骑行环浦东，风景太美了！🚴‍♂️',
      description: '找到了一个骑行搭子，一起骑行环浦东，沿途风景超级美，还在陆家嘴停留拍照。',
      images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&q=80'],
      category: '骑行',
      categoryEmoji: '🚴',
      likes: 567,
      comments: 2,
      createdAt: DateTime.now().subtract(Duration(hours: 8)),
      commentList: [
        {
          'userName': '第零号用户',
          'userAvatar': 'https://picsum.photos/100/100?random=37',
          'content': '骑行真的很爽！',
          'time': '5小时前',
        },
        {
          'userName': '半盏流年',
          'userAvatar': 'https://picsum.photos/100/100?random=38',
          'content': '风景确实很美',
          'time': '4小时前',
        },
      ],
    ),
    Feed(
      id: 'f5',
      userName: 'Emma',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      rating: 4.9,
      ratingLabel: '超赞',
      title: '米其林餐厅品鉴，美食搭子真的绝了！🍽️',
      description: '和美食搭子一起去了新开的米其林餐厅，每一道菜都讨论得很深入，找到了真正懂吃的人！',
      images: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80'],
      category: '品鉴',
      categoryEmoji: '🍷',
      likes: 678,
      comments: 5,
      createdAt: DateTime.now().subtract(Duration(hours: 10)),
      commentList: [
        {
          'userName': 'Orbit',
          'userAvatar': 'https://picsum.photos/100/100?random=39',
          'content': '米其林餐厅真的很不错',
          'time': '6小时前',
        },
        {
          'userName': '独白',
          'userAvatar': 'https://picsum.photos/100/100?random=40',
          'content': '美食搭子最棒了',
          'time': '5小时前',
        },
        {
          'userName': '半山听雨',
          'userAvatar': 'https://picsum.photos/100/100?random=41',
          'content': '我也想去尝尝',
          'time': '4小时前',
        },
        {
          'userName': '岛屿来信',
          'userAvatar': 'https://picsum.photos/100/100?random=42',
          'content': '下次一起去吧',
          'time': '3小时前',
        },
        {
          'userName': '西瓜冰',
          'userAvatar': 'https://picsum.photos/100/100?random=43',
          'content': '这个搭子真的有品味',
          'time': '2小时前',
        },
      ],
    ),
    Feed(
      id: 'f6',
      userName: 'Tom',
      userAvatar: 'https://picsum.photos/100/100?random=24',
      rating: 4.7,
      ratingLabel: '很赞',
      title: '音乐节现场，和搭子一起嗨翻天！🎵',
      description: '周末去了音乐节，和搭子一起在现场跳舞，整个氛围超级棒，完全停不下来！',
      images: ['https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80'],
      category: '音乐',
      categoryEmoji: '🎵',
      likes: 834,
      comments: 4,
      createdAt: DateTime.now().subtract(Duration(hours: 12)),
      commentList: [
        {
          'userName': '心动悖论',
          'userAvatar': 'https://picsum.photos/100/100?random=44',
          'content': '音乐节真的很嗨',
          'time': '7小时前',
        },
        {
          'userName': '保安大队长',
          'userAvatar': 'https://picsum.photos/100/100?random=45',
          'content': '我也想去音乐节',
          'time': '6小时前',
        },
        {
          'userName': '废话文学家',
          'userAvatar': 'https://picsum.photos/100/100?random=46',
          'content': '搭子真的很重要',
          'time': '5小时前',
        },
        {
          'userName': 'Dust',
          'userAvatar': 'https://picsum.photos/100/100?random=47',
          'content': '下次一起去吧',
          'time': '4小时前',
        },
      ],
    ),
    Feed(
      id: 'f7',
      userName: 'Sarah',
      userAvatar: 'https://picsum.photos/100/100?random=23',
      rating: 5.0,
      ratingLabel: '完美搭子',
      title: '露营之旅，在星空下聊天到天亮 🏕️',
      description: '和户外搭子一起去露营，在帐篷里聊天聊到天亮，看到了最美的日出，这就是我想要的搭子体验！',
      images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=400&q=80'],
      category: '户外',
      categoryEmoji: '🏕️',
      likes: 945,
      comments: 3,
      createdAt: DateTime.now().subtract(Duration(hours: 14)),
      commentList: [
        {
          'userName': '小甜柚',
          'userAvatar': 'https://picsum.photos/100/100?random=48',
          'content': '露营真的很浪漫',
          'time': '8小时前',
        },
        {
          'userName': '帅到被判无期',
          'userAvatar': 'https://picsum.photos/100/100?random=49',
          'content': '星空真的很美',
          'time': '7小时前',
        },
        {
          'userName': '贝贝',
          'userAvatar': 'https://picsum.photos/100/100?random=50',
          'content': '我也想去露营',
          'time': '6小时前',
        },
      ],
    ),
    Feed(
      id: 'f8',
      userName: 'Lisa',
      userAvatar: 'https://picsum.photos/100/100?random=21',
      rating: 4.8,
      ratingLabel: '很赞',
      title: '看展新体验，艺术搭子真的有品味！🎨',
      description: '和艺术搭子一起看了当代艺术展，讨论每一件作品的含义，收获很大！',
      images: ['https://images.unsplash.com/photo-1561214115-6d2f1b0609fa?w=400&q=80'],
      category: '看展',
      categoryEmoji: '🎨',
      likes: 612,
      comments: 2,
      createdAt: DateTime.now().subtract(Duration(hours: 16)),
      commentList: [
        {
          'userName': '寄与风',
          'userAvatar': 'https://picsum.photos/100/100?random=51',
          'content': '艺术展真的很有意思',
          'time': '9小时前',
        },
        {
          'userName': '春山',
          'userAvatar': 'https://picsum.photos/100/100?random=52',
          'content': '艺术搭子最棒了',
          'time': '8小时前',
        },
      ],
    ),
    Feed(
      id: 'f9',
      userName: 'Jack',
      userAvatar: 'https://picsum.photos/100/100?random=22',
      rating: 4.6,
      ratingLabel: '很赞',
      title: '火锅聚餐，找到了真正的吃货搭子！🍲',
      description: '和吃货搭子一起去吃火锅，讨论每一种食材的搭配，完全是美食知己！',
      images: ['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80'],
      category: '饭局',
      categoryEmoji: '🍲',
      likes: 523,
      comments: 3,
      createdAt: DateTime.now().subtract(Duration(hours: 18)),
      commentList: [
        {
          'userName': '沉默的回声',
          'userAvatar': 'https://picsum.photos/100/100?random=53',
          'content': '火锅真的很好吃',
          'time': '10小时前',
        },
        {
          'userName': '脑子有黑洞',
          'userAvatar': 'https://picsum.photos/100/100?random=54',
          'content': '吃货搭子最棒了',
          'time': '9小时前',
        },
        {
          'userName': '扫地僧',
          'userAvatar': 'https://picsum.photos/100/100?random=55',
          'content': '我也想去吃火锅',
          'time': '8小时前',
        },
      ],
    ),
  ];

  static final List<String> categories = [
    '全部分享',
    '观影',
    '看展',
    '品鉴',
    '饭局',
    '音乐',
    '骑行',
    '户外',
  ];

  static final List<String> categoryEmojis = [
    '',
    '🍿',
    '🎨',
    '🍷',
    '🍲',
    '🎵',
    '🚴',
    '🏕️',
  ];

  static final List<String> allCities = [
    '全部',
    '北京市',
    '上海市',
    '广州市',
    '深圳市',
    '杭州市',
    '南京市',
    '苏州市',
    '武汉市',
    '成都市',
    '西安市',
  ];

  // 获取特定用户的活动
  static List<Activity> getActivitiesByUserName(String userName) {
    return homeActivities.where((activity) => activity.userName == userName).toList();
  }

  // 为用户生成一致的但不同的个人资料数据
  static Map<String, dynamic> getUserProfileData(String userName) {
    // 使用用户名的哈希值生成一致的随机数
    int hash = userName.hashCode.abs();
    
    // 生成评分 (4.0 - 5.0)
    double rating = 4.0 + (hash % 100) / 100.0;
    
    // 生成粉丝数 (50 - 200)
    int followers = 50 + (hash ~/ 100) % 151;
    
    // 生成关注数 (30 - 150)
    int following = 30 + (hash ~/ 1000) % 121;
    
    return {
      'rating': double.parse(rating.toStringAsFixed(1)),
      'followers': followers,
      'following': following,
    };
  }
}
